### ISSUE TITLE
Currently not working in Redmine 5.x`

### ISSUE THREAD

**Issue by whotopia** [mikitex70/redmine_reveal#7]
```
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
LoadError: cannot load such file -- redmine_reveal
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies/zeitwerk_integration.rb:51:in `require_dependency'
/home/finddx-rm/plugins/redmine_reveal/after_init.rb:2:in `<top (required)>'
/home/finddx-rm/redmine-5.0.0/plugins/redmine_reveal/init.rb:16:in `require_relative'
/home/finddx-rm/redmine-5.0.0/plugins/redmine_reveal/init.rb:16:in `<top (required)>'
/home/finddx-rm/redmine-5.0.0/lib/redmine/plugin_loader.rb:31:in `load'
/home/finddx-rm/redmine-5.0.0/lib/redmine/plugin_loader.rb:31:in `run_initializer'
/home/finddx-rm/redmine-5.0.0/lib/redmine/plugin_loader.rb:108:in `each'
/home/finddx-rm/redmine-5.0.0/lib/redmine/plugin_loader.rb:108:in `block in load'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:427:in `instance_exec'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:604:in `block (2 levels) in default_terminator'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:603:in `catch'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:603:in `block in default_terminator'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:199:in `block in halting'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `block in invoke_before'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `each'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:512:in `invoke_before'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/callbacks.rb:105:in `run_callbacks'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/reloader.rb:88:in `prepare!'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/application/finisher.rb:124:in `block in <module:Finisher>'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `instance_exec'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:32:in `run'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `call'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/initializable.rb:60:in `run_initializers'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/application.rb:391:in `initialize!'
/home/finddx-rm/redmine-5.0.0/config/environment.rb:16:in `<top (required)>'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `block in require'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.4.7/lib/active_support/dependencies.rb:332:in `require'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/application.rb:367:in `require_environment!'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.4.7/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/finddx-rm/.rbenv/versions/2.7.2/bin/rake:23:in `load'
/home/finddx-rm/.rbenv/versions/2.7.2/bin/rake:23:in `<top (required)>'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:58:in `load'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:23:in `run'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/cli.rb:483:in `exec'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/cli.rb:31:in `dispatch'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/cli.rb:25:in `start'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/exe/bundle:48:in `block in <top (required)>'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/home/finddx-rm/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.3.11/exe/bundle:36:in `<top (required)>'
/home/finddx-rm/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/home/finddx-rm/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'
```

**Comment by mikitex70** [comment]
Hello @whotopia, I know, I'm working on it but lately my free time is very little...
I hope to be able to release a working version for Redmine 5 over the next weekend.

**Comment by mikitex70** [comment]
Hi @whotopia,
I've release version `v0.4.0` of the plugin. Now it works with Remind 5.
There is also an upgrade of the `reveal.js` library, so there are some news. See the `demo.textile` for some examples.

**Comment by mikitex70** [comment]
No more feedback. I close the issue.
Feel free to open another one if that's the case.
